#!/bin/sh

if test -z "$PVS_LIBRARY_PATH"; then
    export PVS_LIBRARY_PATH=$1/pvs
else
    export PVS_LIBRARY_PATH=$1/pvs:$PVS_LIBRARY_PATH
fi
sh $(locate  why3-modify-pvs | grep /usr) $3
shift
exec "$@"
