#!/bin/sh

if test -z "$PVS_LIBRARY_PATH"; then
    export PVS_LIBRARY_PATH=$1/pvs
else
    export PVS_LIBRARY_PATH=$1/pvs:$PVS_LIBRARY_PATH
fi
f=$(locate  why3-modify-pvs | grep /usr)
[ -n "$f" ] && sh $f $3
shift
exec "$@"
